services:
  # フロントエンドサービス
  frontend:
    build:
      context: ./frontend
    volumes:
      - .:/workspaces/coffeebeans:cached
      - /workspaces/coffeebeans/frontend/node_modules # <--- node_modulesのパスを更新

    ports:
      - "5173:5173"

  # バックエンドサービス
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"