# readmeをgistに自動で同期するgithub actionsの設定ファイル
name: Sync README.md to Gist

on:
  push:
    branches:
      - main  # README.mdがあるメインのブランチ名に合わせて変更してください (main, masterなど)
    paths:
      - 'README.md' # README.mdファイルへの変更があった時のみ実行

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync README to Gist
        env:
          GIST_PAT: ${{ secrets.GIST_PAT }}
          GIST_ID: ${{ secrets.GIST_ID }}
          FILE_PATH: 'README.md'
        run: |
          # jq を使って安全にJSONペイロードを生成する
          JSON_PAYLOAD=$(jq -n \
                            --arg desc "Project README (auto-updated)" \
                            --arg content "$(cat $FILE_PATH)" \
                            '{description: $desc, files: {"README.md": {content: $content}}}')
          # Gist APIを叩いてファイルを更新
          curl -s -L -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GIST_PAT" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/gists/$GIST_ID" \
            -d "$JSON_PAYLOAD"
